import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button } from "../components/Button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <section className="home-hero ">
          <div className="home-hero__details inner-container">
            <h1 className="fs-800 fw-black">
              <span className="d-block">Great coffee</span>{" "}
              <span className="d-block">made simple.</span>
            </h1>
            <p>
              Start your mornings with the world’s best coffees. Try our
              expertly curated artisan coffees from our best roasters delivered
              directly to your door, at your schedule.
            </p>
            <Button type={"link"}>Create your plan</Button>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
