import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../components/Button";
import { CoffeeCollectionCard } from "../components/CoffeeCollectionCard";
import { HowItWorksCard } from "../components/HowItWorksCards";
import { WhyUsCards } from "../components/WhyUsCards";
import { coffeeCollectionData } from "../data/coffeeCollectionData";
import { howItWorksData } from "../data/how-it-works-data";
import { whyUsData } from "../data/whyUsData";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <section className="home-hero ">
          <div className="home-hero__details inner-container">
            <h1 className="fs-800 fw-black">
              <span className="d-block">Great coffee</span>{" "}
              <span className="d-block">made simple.</span>
            </h1>
            <p>
              Start your mornings with the world’s best coffees. Try our
              expertly curated artisan coffees from our best roasters delivered
              directly to your door, at your schedule.
            </p>
            <Button type={"link"}>Create your plan</Button>
          </div>
        </section>
        <section className="home-collection">
          <h2 className="fw-black home-collection__title d-block t-center fs-900 ff-serif">
            our collection
          </h2>
          <div className="grid-container home-collection__grid">
            {coffeeCollectionData.map((data, index) => (
              <CoffeeCollectionCard
                key={index}
                title={data.title}
                image={data.image}
                description={data.description}
              />
            ))}
          </div>
        </section>
        <section className="why-us t-center  ">
          <h2 className="fw-black  d-block t-center fs-700 ff-serif">
            Why choose us?
          </h2>
          <p>
            A large part of our role is choosing which particular coffees will
            be featured in our range. This means working closely with the best
            coffee growers to give you a more impactful experience on every
            level.
          </p>
          <div className="grid-container why-us__grid inner-container ">
            {whyUsData.map((data, index) => (
              <WhyUsCards
                key={index}
                title={data.title}
                image={data.image}
                description={data.description}
                truck={data.truck}
              />
            ))}
          </div>
        </section>
        <section className="how-it-works inner-container ">
          <h2 className="ff-serif fw-black fs-500">How it works</h2>
          <div className="grid-container how-it-works__grid ">
            {howItWorksData.map((data, index) => (
              <HowItWorksCard
                key={index}
                number={data.number}
                title={data.title}
                description={data.description}
              />
            ))}
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
